#!/bin/bash

#     -----------
#     | | | | | |
#     | | | | | |
#     | | | | | |
#     | | | | | |
#     -----------


LAYOUT_CHANGE()
{
	# Save current node
	CURRENT_NODE=$(bspc query -N -n)

	# Set the splitType of all internal nodes
	for loop in $(LIST_INTER); do
		SET_SPLIT_TYPE $loop horizontal
	done

	# Balance the ratios of the nodes
	bspc node `RETURN_INTER 1` -B

	# Move the current to the first
	UPDATE_LEAFS
	bspc node -f $CURRENT_NODE
	bspc node -s $(RETURN_LEAFS 1)
}
