#!/bin/bash

#     -----------
#     |  |   |  |
#     |  |   |  |
#     |---------|
#     |         |
#     -----------


LAYOUT_CHANGE()
{
	# Save current node
	CURRENT_NODE=$(bspc query -N -n)

	# Move all leaf node to the first internal node
	for loop in $(LIST_LEAFS); do
		MOVE_LEAF $loop $(RETURN_INTER 1)
	done

	# Flip the first internal node
	bspc node `RETURN_INTER 1` -F horizontal

	# Set the splitType of some internal nodes
	for loop in $(LIST_INTER | cut -d' ' -f2-); do
		SET_SPLIT_TYPE $loop horizontal
	done

	# Set the splitType of the first internal node
	SET_SPLIT_TYPE `RETURN_INTER 1` horizontal

	# Balance the ratios of the nodes
	bspc node `RETURN_INTER 2` -B


	# Move the current to the first
	UPDATE_LEAFS
	bspc node -f $CURRENT_NODE
	bspc node -s $(RETURN_LEAFS $LEAFS_NUMBER)
}
