yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: node-modules
preferInteractive: true

initLicense: MIT
initVersion: 1.0.0

initFields:
    author: "User Name"
    main: "index.js"
    description: "Project description"
    keywords: 
        '[ "keyword" ]'
    scripts:
        start: "node server.js"
