#!/bin/bash

######### POLYGON PROMPT #########

# Make to be usaed with Bash



# Sucess colors
BACK_COLOR_SUCCESS=$BACK_COLOR_3
CHAR_COLOR_SUCCESS=$CHAR_COLOR_3

# Staged Colors
BACK_COLOR_STAGED=$BACK_COLOR_4
CHAR_COLOR_STAGED=$CHAR_COLOR_4



# Git prompt part
UPDATE_GIT_ARCHIVES_PROMPT()
{
	# Include GIT TOOLS FOR BASH
	source $HOME'/.bash/tools/git'

	if [ "_$(git status -s 2> /dev/null)" != '_' -o "_$(git stash list)" != "_" ]; then
		echo " …$UNTRACKED +$MODIFIED ×$DELETED | •$STAGED ➤+$MODIFIED_STAGED ➤×$DELETED_STAGED | ⚑ $STASHED_ENTRIES "
	else
		echo '✔ '
	fi
}



# Update prompt
PROMPT_REFRESH()
{
	# Change the colors in case of error
	if [ $1 != 0 ]; then
		BACK_COLOR_3=$BACK_COLOR_ERROR
		CHAR_COLOR_3=$CHAR_COLOR_ERROR
	else
		BACK_COLOR_3=$BACK_COLOR_SUCCESS
		CHAR_COLOR_3=$CHAR_COLOR_SUCCESS
	fi


	EXPORT_INFO_BG=''
	EXPORT_INFO_TEXT=''

	# Git tool prompt
	ls '.git/' 2> '/dev/null' > '/dev/null' &&
	{
		# Git prompt colors
		if [ "_$(git status -s)" != '_' -o "_$(git stash list)" != "_" ]; then
			BACK_COLOR_4=$BACK_COLOR_GIT
			CHAR_COLOR_4=$CHAR_COLOR_GIT
		else
			BACK_COLOR_4=$BACK_COLOR_STAGED
			CHAR_COLOR_4=$CHAR_COLOR_STAGED
		fi

		# Git pormpt info
		PROMPT_INFO="  $(git status -sb | sed -n '1p' | cut -d' ' -f2-) `UPDATE_GIT_ARCHIVES_PROMPT`"

		# Try not change this. Change preferably the 'PROMPT_INFO' variable
		EXPORT_INFO_BG='\[\033[48;5;${BACK_COLOR_4}m\]'
		EXPORT_INFO_TEXT='\[\033[38;5;${CHAR_COLOR_4}m\]${PROMPT_INFO}\[$(tput sgr0)\]\[\033[38;5;${BACK_COLOR_4}m\]'
	}
	export PS1="\n\[\033[38;5;${CHAR_COLOR_1}m\]\[\033[48;5;${BACK_COLOR_1}m\] \s \[\033[38;5;${BACK_COLOR_1}m\]\[\033[48;5;${BACK_COLOR_2}m\]\[\033[38;5;${CHAR_COLOR_2}m\] \u \[$(tput sgr0)\]\[\033[38;5;${BACK_COLOR_2}m\]\[\033[48;5;${BACK_COLOR_3}m\]\[\033[38;5;${CHAR_COLOR_3}m\] \w \[$(tput sgr0)\]\[\033[38;5;${BACK_COLOR_3}m\]${EXPORT_INFO_BG}${EXPORT_INFO_TEXT}\n\[\033[48;5;${BACK_COLOR_5}m\]\[\033[38;5;${CHAR_COLOR_5}m\]\$\[$(tput sgr0)\]\[\033[38;5;${BACK_COLOR_5}m\] \[$(tput sgr0)\]$TEXT_COLOR"
}



# Another prompt Variables

PROMPT_COMMAND='PROMPT_REFRESH $?'

export PS2="\[\033[48;5;${BACK_COLOR_4}m\] \[$(tput sgr0)\]  $TEXT_COLOR"

export PS4="\[\033[48;5;${BACK_COLOR_1}m\] \[$(tput sgr0)\]  \[$(tput sgr0)\]$TEXT_COLOR"
