#!/bin/bash

# OBS.: This is experimental. You need to delete the '~/Desktop' directory


set -e

DESKDIRS=("$HOME/.Desktops" "$HOME/.DesktopsSync")


# Show help message
HELP_MSG()
{
	echo -e '\nusage: chdesk [command]\n'
	echo -e 'Commands:\n'

	echo '  init - Start chdesk (move current desktop to folder with desktops)'
	echo '  list | ls - list the available desktops'
	echo '  list-base | ls-base - list the folders with the desktops'
	echo '  list-names | ls-names - list the labels of the desktops (1 label per line)'
	echo '  show path | show name - show the path or the label of the current desktop'
	echo '  add | make <index> <name> - create a new desktop with the label <name> in the <index> folder'
	echo '  cp | copy <src_name> <dest_path> - copy the <src_name> desktop to a the path <dest_name>'
	echo '  rm | remove | dell <name> - delete a desktop witk the label <name>'
	echo '  change <name> - change to the desktop with the label <name>'
	echo '  help | -h | --help - show this message'

	echo -e '\n\nError codes:'
	echo '  1: unrecognized option'
	echo '  2: wrong number of parameters'
	echo '  3: trying to create an existing desktop'
	echo '  4: non-existing desktop'
}


# Check the parameters number
#
# $1: Current number of parameters
# $2: Correct number of parameters
CURRENT_NUMBER_OF_PARAMETERS="$#"
CHECK_PARAMETERS_NUMBER()
{
	if [[ "$1" != "$CURRENT_NUMBER_OF_PARAMETERS" ]]; then
		echo -e "\nERROR! Wrong number of parameters. See the help message:"
		HELP_MSG
		exit 2
	fi
}


# Check if a Desktop exists
#
# $1: Desktop name (not the path)
GET_DESKTOP_PATH()
{
	HAS_DESKTOP="false"

	for base_folder in "${DESKDIRS[@]}"; do
		DESKTOP_PATH="$base_folder/$1"

		if [[ -d "$DESKTOP_PATH" ]]; then
			echo "$DESKTOP_PATH"
			HAS_DESKTOP="true"
			break
		fi
	done

	if [[ "$HAS_DESKTOP" == "false" ]]; then
		echo "None"
	fi
}


GET_ACTIVE_DESKTOP()
{
	DESKTOP_PATH=$(readlink ~/Desktop)
	NAME=$(basename "$DESKTOP_PATH")

	if [[ $(GET_DESKTOP_PATH "$NAME") == None ]]; then
		echo "None"

	else
		case "$1" in
			name)
				echo "$NAME"
				;;

			path)
				echo "$DESKTOP_PATH"
				;;

			*)
				echo "None"
				;;
		esac
	fi
}


case "$1" in
	# Init chdesk
	init) CHECK_PARAMETERS_NUMBER 1
		# Directories with desktops
		for base_folder in "${DESKDIRS[@]}"; do
			mkdir -p "$base_folder"
		done

		# If the current '~/Desktop' is not link, makes it a new possible Desktop, and switches to it.
		if [[ ! -L ~/Desktop ]]; then
			NEW_DESKTOP=$(date +%F-%T)
			mv ~/Desktop "${DESKDIRS[0]}/$NEW_DESKTOP"
			"$0" change "$NEW_DESKTOP"
		fi
		;;

	# List all "Desktops"
	list | ls ) CHECK_PARAMETERS_NUMBER 1
		for base_folder in "${DESKDIRS[@]}"; do
			ls "$base_folder"
		done

		echo -e "\nActive: $(GET_ACTIVE_DESKTOP name)"
		;;

	list-base | ls-base ) CHECK_PARAMETERS_NUMBER 1
		for base_folder in "${DESKDIRS[@]}"; do
			echo "$base_folder"
		done
		;;

	list-names | ls-names ) CHECK_PARAMETERS_NUMBER 1
		for base_folder in "${DESKDIRS[@]}"; do
			ls -1 "$base_folder"
		done
		;;

	show | show-active ) CHECK_PARAMETERS_NUMBER 2
		GET_ACTIVE_DESKTOP "$2"
		;;

	# Create a new "Desktop"
	add | make ) CHECK_PARAMETERS_NUMBER 3
		# Does not create if it already exists
		if [[ $(GET_DESKTOP_PATH "$3") != "None" ]]; then
			echo -e '\nThis Desktop already exists! Choose other name.\n'
			exit 3

		# Creates the new Desktop
		else
			mkdir -p "${DESKDIRS[$2]}/$3"
		fi
		;;

	# Copy a existing "Desktop"
	cp | copy ) CHECK_PARAMETERS_NUMBER 3
		# Does not copy if the Desktop does not exist
		SRC_PATH=$(GET_DESKTOP_PATH "$2")

		if [[ "$SRC_PATH" == "None" ]]; then
			echo -e '\nThis Desktop does not exists!\n'
			exit 4
		fi

		# Does not copy if the destination already exists
		if [[ -e "$3" || -L "$3" ]]; then
			echo -e '\nThe destination already exists! Choose other name.\n'
			exit 3
		fi

		# Copies the Desktop
		cp -r "$SRC_PATH" "$3"
		;;

	# Remove a existing "Desktop"
	rm | remove | dell ) CHECK_PARAMETERS_NUMBER 2
		DESKTOP_PATH=$(GET_DESKTOP_PATH "$2")

		# Does not delete if the Desktop does not exist
		if [[ "$DESKTOP_PATH" == "None" ]]; then
			echo -e '\nThis Desktop does not exists!\n'
			exit 4
		fi

		# Deletes
		rm -r "$DESKTOP_PATH"
		;;

	# Change to the "Desktop"
	change ) CHECK_PARAMETERS_NUMBER 2
		DESKTOP_PATH=$(GET_DESKTOP_PATH "$2")

		# Does not change if it does not exists
		if [[ "$DESKTOP_PATH" == "None" ]]; then
			echo -e '\nThis Desktop does not exists!\n'
			exit 4
		fi

		# Changes the Desktop
		ln -dsfT "$DESKTOP_PATH" ~/Desktop

		# Restarts the Xfdesktop (if in xfce)
		if [ "$XDG_CURRENT_DESKTOP" == 'XFCE' ]; then
			xfdesktop -Q
			xfdesktop -R &
		fi
		;;

	# Show help message
	help | -h | --help ) CHECK_PARAMETERS_NUMBER 1
		HELP_MSG;;

	# Error because there are no parameters
	"" ) NUMBER_ERROR $# 1;;

	# If there is no compatible option
	* )
		echo "Command: 'chdesk'; unrecognized option: '$1'"
		exit 1
		;;
esac


# vim: nobackup
