#!/bin/bash


UMOUNT_KEESHARE()
{
	# Unmounts and removes the folder
	fusermount -u ~/.keeshare/folder-to-sync
	rm -r ~/.keeshare/folder-to-sync
}


case "$1" in
	mount )
		UMOUNT_KEESHARE

		# Creates the folder and mounts
		mkdir -p ~/.keeshare/folder-to-sync
		rclone mount KeeShareConfig:/ ~/.keeshare/folder-to-sync &
		;;

	umount )
		UMOUNT_KEESHARE
		;;

	* )
		echo "Command: 'keeshare-backend'; unrecognized option: '$1'"
		exit 1
		;;
esac


# vi: nobackup
