#!/bin/bash


# Show help message
HELP_MSG()
{
	echo -e '\nusage: set-theme [command] <parameters>\n'
	echo -e 'Commands:\n'

	echo '  -g | --gtk <name> - Set the current GTK theme to <name>'
	echo '  -i | --icon <name> - Set the current icon theme to <name>'
	echo '  -c | --cursor <name> - Set the current cursor theme to <name>'
	echo '  --fix-cursor - Fix the cursor theme (some login manager can change it)'
	echo '  help | -h | --help - show this message'

	echo -e '\n\nError codes:'
	echo '  1: unrecognized option'
	echo '  2: wrong number of parameters'
}


# Check the parameters number
#
# $1: Current number of parameters
# $2: Correct number of parameters
NUMBER_ERROR () {
	if [[ "$1" != "$2" ]]; then
		echo -e "\nERROR! Wrong number of parameters.\n"
		exit 2
	fi
}


# Change a file attribute
#
# $1: file path
# $2: Attribute pathern
# $3: Attribute value
CHANGE_FILE_ATTRIBUTE()
{
	# Change the file attribute
	sed -i s/"${2}.*"/"${2}=${3}"/ "$1"
}


# Get a file attribute
#
# $1: File path
# $2: Attribute name
GET_FILE_ATTRIBUTE()
{
	cat "$1" | awk "/$2/" | sed -n 1p | sed 's/.*=//g'
}


# Main code
case "$1" in
	# Set GTK theme
	'-g' | '--gtk' ) NUMBER_ERROR $# 2
		# GTK 2
		CHANGE_FILE_ATTRIBUTE ~/.gtkrc-2.0 'gtk-theme-name' "\"$2\""

		# GTK 3
		CHANGE_FILE_ATTRIBUTE ~/.config/gtk-3.0/settings.ini 'gtk-theme-name' "$2"

		# Gnome
		gsettings set org.gnome.desktop.interface gtk-theme "$2"
		;;

	# Set icon theme
	'-i' | '--icon') NUMBER_ERROR $# 2
		# GTK 2
		CHANGE_FILE_ATTRIBUTE ~/.gtkrc-2.0 'gtk-icon-theme-name' "\"$2\""

		# GTK 3
		CHANGE_FILE_ATTRIBUTE ~/.config/gtk-3.0/settings.ini 'gtk-icon-theme-name' "$2"

		# Default Icon Theme
		CHANGE_FILE_ATTRIBUTE ~/.icons/default/index.theme 'Inherits' "$2"

		# Gnome
		gsettings set org.gnome.desktop.interface icon-theme "$2"
		;;

	# Set cursor theme
	'-c' | '--cursor' ) NUMBER_ERROR $# 2
		# GTK 2
		CHANGE_FILE_ATTRIBUTE ~/.gtkrc-2.0 'gtk-cursor-theme-name' "\"$2\""

		# GTK 3
		CHANGE_FILE_ATTRIBUTE ~/.config/gtk-3.0/settings.ini 'gtk-cursor-theme-name' "$2"

		# Gnome
		gsettings set org.gnome.desktop.interface cursor-theme "$2"

		# Mate
		gsettings set org.mate.peripherals-mouse cursor-theme "$2"

		# Xfce
		xfconf-query --channel xsettings --property /Gtk/CursorThemeName --set "$2"

		# X server
		echo "Xcursor.theme: $2" | xrdb
		xsetroot -cursor_name left_ptr
		;;

	# Fix cursor theme. Some login managers can change the cursor theme.
	# This option is needed to restore the cursor to the correct one.
	'--fix-cursor' ) NUMBER_ERROR $# 1
		# X server
		echo "Xcursor.theme: $(GET_FILE_ATTRIBUTE ~/.config/gtk-3.0/settings.ini gtk-cursor-theme-name)" | xrdb
		xsetroot -cursor_name left_ptr
		;;

	# Show help message
	help | -h | --help ) NUMBER_ERROR $# 1
		HELP_MSG;;

	# Error because there are no parameters
	"" ) NUMBER_ERROR $# 1;;

	# If there is no compatible option
	* )
		echo "Command: 'bspc-layout'; unrecognized option: '$1'"
		exit 1
		;;
esac


# vim: nobackup
