#! /bin/sh

sxhkd &
compton &
nitrogen --restore &
pulseaudio --start &
polybar topbar &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d I II III IV V VI VII VIII IX


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  '#666666'
bspc config focused_border_color '#aaaaaa'

bspc config border_width         1
bspc config window_gap           0

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



DISP_WIDTH=$(xdpyinfo | grep dimensions | cut -d' ' -f7 | cut -d'x' -f1)
DISP_HEIGHT=$(xdpyinfo | grep dimensions | cut -d' ' -f7 | cut -d'x' -f2)

for loop in 'Gufw.py' 'Nm-connection-editor' 'Nm-connection-editor' 'File-roller' 'Gpick' 'processing-app-Base' 'Pdfarranger'; do
	bspc rule -a $loop state=floating;
done

bspc rule -a Pavucontrol state=floating rectangle=700x400
bspc rule -a Xfce4-appfinder state=floating rectangle=400x480+`python -c "print($DISP_WIDTH/2 - 200)"`+`python -c "print($DISP_HEIGHT/2 - 240)"`
