#!/bin/bash

########## GIT TOOLS FOR BASH ##########

# Make to be usaed with Bash



## Branchs Archives

# Declare git info variables
local -i UNTRACKED=0
local -i STAGED=0
local -i MODIFIED=0
local -i MODIFIED_STAGED=0
local -i DELETED=0
local -i DELETED_STAGED=0
local -i STASHED_ENTRIES=0

# Update the number os archives
if [ "_$(git status -s 2> /dev/null)" != '_' -o "_$(git stash list)" != "_" ]; then
	for ((loop=1;loop<=`git status -s | wc -l`; loop++))
	{
		LINE=$(git status -s | sed -n "${loop}p")

		CHAR_0=${LINE:0:1}
		CHAR_1=${LINE:1:1}

		# Staged Archives
		case "_$CHAR_0" in
			'_A' ) STAGED+=1;;
			'_M' ) MODIFIED_STAGED+=1;;
			'_D' ) DELETED_STAGED+=1;;
		esac

		# Not Staged Archives
		case "_$CHAR_1" in
			'_?' ) UNTRACKED+=1;;
			'_M' ) MODIFIED+=1;;
			'_D' ) DELETED+=1;;
		esac

	}

	STASHED_ENTRIES=$(git stash list | wc -l)
fi



## Branch Tracking

# Branchs
local BRANCH=$(git branch | awk '/\*/' | cut -d' ' -f2-)
local REMOTE="origin/${BRANCH}"

local -i BRANCH_AHEAD=0


if [ "$(echo "$BRANCH" | awk '/\(/')" = '' ]; then

	if [ "$(git show-branch "$REMOTE" 2> '/dev/null')" != '' ]; then
	
		# Branch SHA1
		local BRANCH_SHA=$(git show-branch --sha1-name "$BRANCH" | sed 's/^.*\[//' | sed 's/\].*$//')
		local REMOTE_SHA=$(git show-branch --sha1-name "$REMOTE" | sed 's/^.*\[//' | sed 's/\].*$//')

		# Git log variables
		local loop
		local LOG=$(git log --oneline "$BRANCH" "$REMOTE" | cut -d' ' -f1)

		# Branch relative position in LOG
		local -i NUM_BRANCH=0
		local -i NUM_REMOTE=0
		local -i NUM_LOOP=0

		for loop in $LOG; do
			if [ "$loop" = "$BRANCH_SHA" ]; then   # Local branch number
				NUM_BRANCH=$NUM_LOOP

			elif [ "$loop" = "$REMOTE_SHA" ]; then # Remote branch number
				NUM_REMOTE=$NUM_LOOP
			fi

			NUM_LOOP+=1
		done

		# Set the AHEAD of branchs
		BRANCH_AHEAD="${NUM_REMOTE}-${NUM_BRANCH}"

	else
		# Set the AHEAD of branchs to 'L'
		unset BRANCH_AHEAD
		local BRANCH_AHEAD='L'
	fi

	# Unset unnecessary variables
	unset BRANCH_SHA
	unset REMOTE_SHA
	unset loop
	unset LOG
	unset NUM_BRANCH
	unset NUM_REMOTE
	unset NUM_LOOP
fi
